/**
 * Expo config plugin: a StoreKit configuration for local builds.
 *
 * On a simulator, and on any build that is not signed for the App Store,
 * StoreKit answers product requests from a `.storekit` file attached to
 * the Xcode scheme — never from App Store Connect. Without one, RevenueCat
 * gets its offering back from its own API with two product ids, asks
 * StoreKit for them, receives nothing, and the paywall shows "—" where the
 * prices go. `ios/` is regenerated by prebuild, so the file lives at
 * `storekit/Products.storekit` and this plugin puts it in place each time:
 * copied next to the project, referenced from the main group, and named
 * in the shared scheme's launch action.
 *
 * The prices in the file are the API's defaults (4,99 € / 49,99 €, 3-day
 * trial on the yearly plan). They only ever show on local builds; a store
 * build reads the real ones from App Store Connect.
 */
const fs = require("fs");
const path = require("path");
const { withDangerousMod, withXcodeProject } = require("@expo/config-plugins");

const SOURCE = "storekit/Products.storekit";
const FILE = "Products.storekit";

/** Adds (or replaces) the StoreKit reference in a scheme's LaunchAction. */
function patchScheme(xml, identifier) {
  const ref =
    `      <StoreKitConfigurationFileReference\n` +
    `         identifier = "${identifier}">\n` +
    `      </StoreKitConfigurationFileReference>\n`;
  const without = xml.replace(
    /\s*<StoreKitConfigurationFileReference[\s\S]*?<\/StoreKitConfigurationFileReference>\n?/,
    "\n",
  );
  return without.replace(/(\n\s*<\/LaunchAction>)/, `\n${ref.trimEnd()}$1`);
}

function schemePath(iosRoot, projectName) {
  return path.join(
    iosRoot,
    `${projectName}.xcodeproj`,
    "xcshareddata",
    "xcschemes",
    `${projectName}.xcscheme`,
  );
}

/** Copies the file into ios/ and points the shared scheme at it. */
function applyToIosFolder(projectRoot, iosRoot, projectName) {
  fs.copyFileSync(path.join(projectRoot, SOURCE), path.join(iosRoot, FILE));
  const scheme = schemePath(iosRoot, projectName);
  // Xcode resolves the identifier from <project>.xcodeproj/project.xcworkspace,
  // so a file beside the project is two levels up.
  fs.writeFileSync(scheme, patchScheme(fs.readFileSync(scheme, "utf8"), `../../${FILE}`));
}

/** Lists the file in the project's main group so Xcode shows and syncs it. */
function addToProject(project) {
  if (project.hasFile(FILE)) return project;
  const mainGroup = project.getFirstProject().firstProject.mainGroup;
  project.addFile(FILE, mainGroup, { lastKnownFileType: "text" });
  return project;
}

const withStoreKitConfig = (config) => {
  config = withDangerousMod(config, [
    "ios",
    (c) => {
      applyToIosFolder(
        c.modRequest.projectRoot,
        c.modRequest.platformProjectRoot,
        c.modRequest.projectName,
      );
      return c;
    },
  ]);
  return withXcodeProject(config, (c) => {
    c.modResults = addToProject(c.modResults);
    return c;
  });
};

module.exports = withStoreKitConfig;
module.exports.patchScheme = patchScheme;
module.exports.applyToIosFolder = applyToIosFolder;
module.exports.addToProject = addToProject;
